# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'excel.ui',
# licensing of 'excel.ui' applies.
#
# Created: Mon Apr  1 15:34:10 2019
#      by: pyside2-uic  running on PySide2 5.12.1
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(360, 270)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 341, 251))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 55))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 60))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 191, 31))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setMaximumSize(QtCore.QSize(43, 16777215))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.comboBox_raport_name = QtWidgets.QComboBox(self.horizontalLayoutWidget)
        self.comboBox_raport_name.setObjectName("comboBox_raport_name")
        self.horizontalLayout.addWidget(self.comboBox_raport_name)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(0, 150))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 150))
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 191, 126))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_year = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_year.setObjectName("comboBox_year")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_year)
        self.comboBox_month = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_month.setObjectName("comboBox_month")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_month)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_week = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_week.setObjectName("comboBox_week")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_week)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_producer = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_producer.setObjectName("comboBox_producer")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.comboBox_producer)
        self.label_5 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.label_6 = QtWidgets.QLabel(self.formLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.lineEdit_rows_nr = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_rows_nr.setObjectName("lineEdit_rows_nr")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.lineEdit_rows_nr)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_excel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_excel.setObjectName("pushButton_excel")
        self.horizontalLayout_2.addWidget(self.pushButton_excel)
        self.pushButton_cancel = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.horizontalLayout_2.addWidget(self.pushButton_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Dialog", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Dialog", "Raport", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "nazwa:", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("Dialog", "Filtry", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "rok:", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "miesiac:", None, -1))
        self.label_4.setText(QtWidgets.QApplication.translate("Dialog", "tydzień:", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "producer", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "wiersze: ", None, -1))
        self.pushButton_excel.setText(QtWidgets.QApplication.translate("Dialog", "Excel", None, -1))
        self.pushButton_cancel.setText(QtWidgets.QApplication.translate("Dialog", "Anuluj", None, -1))

