# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'filechose.ui',
# licensing of 'filechose.ui' applies.
#
# Created: Fri Apr 12 10:01:22 2019
#      by: pyside2-uic  running on PySide2 5.12.2
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(469, 307)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 451, 271))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 128))
        self.groupBox.setObjectName("groupBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 20, 431, 102))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.lineEdit_adexpert = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_adexpert.setReadOnly(True)
        self.lineEdit_adexpert.setObjectName("lineEdit_adexpert")
        self.gridLayout.addWidget(self.lineEdit_adexpert, 1, 1, 1, 1)
        self.lineEdit_techedge = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_techedge.setReadOnly(True)
        self.lineEdit_techedge.setObjectName("lineEdit_techedge")
        self.gridLayout.addWidget(self.lineEdit_techedge, 0, 1, 1, 1)
        self.lineEdit_raport3 = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_raport3.setReadOnly(True)
        self.lineEdit_raport3.setObjectName("lineEdit_raport3")
        self.gridLayout.addWidget(self.lineEdit_raport3, 2, 1, 1, 1)
        self.pushButton_raport3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_raport3.setObjectName("pushButton_raport3")
        self.gridLayout.addWidget(self.pushButton_raport3, 2, 2, 1, 1)
        self.pushButton_techedge = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_techedge.setObjectName("pushButton_techedge")
        self.gridLayout.addWidget(self.pushButton_techedge, 0, 2, 1, 1)
        self.pushButton_adexpert = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_adexpert.setObjectName("pushButton_adexpert")
        self.gridLayout.addWidget(self.pushButton_adexpert, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.verticalLayoutWidget)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 124))
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 431, 101))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 3, 0, 1, 1)
        self.comboBox_raports_remove = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_raports_remove.setObjectName("comboBox_raports_remove")
        self.gridLayout_2.addWidget(self.comboBox_raports_remove, 3, 1, 1, 1)
        self.pushButton_addraports = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_addraports.setObjectName("pushButton_addraports")
        self.gridLayout_2.addWidget(self.pushButton_addraports, 1, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.comboBox_raports = QtWidgets.QComboBox(self.gridLayoutWidget_2)
        self.comboBox_raports.setObjectName("comboBox_raports")
        self.gridLayout_2.addWidget(self.comboBox_raports, 0, 1, 1, 1)
        self.pushButton_remove_raports = QtWidgets.QPushButton(self.gridLayoutWidget_2)
        self.pushButton_remove_raports.setObjectName("pushButton_remove_raports")
        self.gridLayout_2.addWidget(self.pushButton_remove_raports, 3, 2, 1, 1)
        self.lineEdit_addraport = QtWidgets.QLineEdit(self.gridLayoutWidget_2)
        self.lineEdit_addraport.setObjectName("lineEdit_addraport")
        self.gridLayout_2.addWidget(self.lineEdit_addraport, 1, 1, 1, 1)
        self.line = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line.setBaseSize(QtCore.QSize(17, 0))
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout_2.addWidget(self.line, 2, 1, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout_2.addWidget(self.line_2, 2, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.gridLayoutWidget_2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_2.addWidget(self.line_3, 2, 2, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.pushButton_addall = QtWidgets.QPushButton(Dialog)
        self.pushButton_addall.setGeometry(QtCore.QRect(387, 280, 75, 23))
        self.pushButton_addall.setObjectName("pushButton_addall")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        Dialog.setWindowTitle(QtWidgets.QApplication.translate("Dialog", "Pliki & Raporty", None, -1))
        self.groupBox.setTitle(QtWidgets.QApplication.translate("Dialog", "Pliki", None, -1))
        self.label_3.setText(QtWidgets.QApplication.translate("Dialog", "Adexpert", None, -1))
        self.label.setText(QtWidgets.QApplication.translate("Dialog", "Techedge", None, -1))
        self.pushButton_raport3.setText(QtWidgets.QApplication.translate("Dialog", "Dodaj", None, -1))
        self.pushButton_techedge.setText(QtWidgets.QApplication.translate("Dialog", "Dodaj", None, -1))
        self.pushButton_adexpert.setText(QtWidgets.QApplication.translate("Dialog", "Dodaj", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Dialog", "raport 3", None, -1))
        self.groupBox_2.setTitle(QtWidgets.QApplication.translate("Dialog", "Raporty", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Dialog", "Raport", None, -1))
        self.label_7.setText(QtWidgets.QApplication.translate("Dialog", "Usuń", None, -1))
        self.pushButton_addraports.setText(QtWidgets.QApplication.translate("Dialog", "Dodaj", None, -1))
        self.label_6.setText(QtWidgets.QApplication.translate("Dialog", "Dodaj", None, -1))
        self.pushButton_remove_raports.setText(QtWidgets.QApplication.translate("Dialog", "Usuń", None, -1))
        self.pushButton_addall.setText(QtWidgets.QApplication.translate("Dialog", "Dodaj", None, -1))

